# Note to self: PyPy is not included here because the installation of Bazaar
# fails on Travis CI even though it works just fine on my local system?! (I'm
# using PyPy from https://launchpad.net/~pypy/+archive/ubuntu/ppa)

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
# Install the dependencies of vcs-repo-mgr before running the test suite.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bzr bzrtools git mercurial
install:
  - pip install pip-accel
  - pip-accel install coveralls
  - LC_ALL=C pip-accel install .
script:
  - make check
  - make test
after_success:
  coveralls
branches:
  except:
    - /^[0-9]/
